version: '3.8'

services:
  app:
    build: .
    container_name: user-balance-avito
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: 90814263
      DB_NAME: userBalanceAvito
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: user-balance-avito-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 90814263
      POSTGRES_DB: userBalanceAvito
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: